#!/usr/bin/env bash

use_nvm() {
	prefix="$(brew --prefix nvm)"

	[ $? -eq 0 ] || return

	source "$prefix/nvm.sh"

	watch_file .nvmrc
	nvm install
	layout node
}

use_context() {
	context=

	[[ -f .envrc.context ]] && context=$(< .envrc.context)

	watch_file ".envrc.context"

	if [[ -n "$context" ]]; then
		context_file=".envrc.$context"

		if [[ -f "$context_file" ]]; then
			source_env "$context_file"
		else
			echo "$context_file missing"
		fi
	fi
}
